server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index saraphone.html index.html;

    location / {
        try_files $uri $uri/ /saraphone.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|mp3|wav|svg|woff|woff2|ttf)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}